// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvpokjgvtybsmezfucvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cG9ramd2dHlic21lemZ1Y3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODYwMjMsImV4cCI6MjA2ODA2MjAyM30.5ed0tjn7va_UeTfz76ayb9-s0hDWn4oTW89Oyu2x_XM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});